version: "3"

services:
    backend:
        image: node:16-alpine
        working_dir: /home/app
        env_file:
            - "./backend/.env"
        volumes:
            -   "./backend/:/home/app"
        ports:
            -   "8081:8081"
        command: "npm run dev"
    mysql:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: nativeip
        volumes:
            -   mysql:/var/lib/mysql

volumes:
    mysql: