version: "3"

services:
    frontend:
        build: ./frontend
        working_dir: /home/app
        # volumes:
            # -   "./frontend/:/home/app"
        ports:
            -   "3000:3000"
        command: "npm run start"
    backend:
        build: ./backend
        working_dir: /home/app
        env_file:
            - "./backend/.env"
        # volumes:
        #     -   "./backend/:/home/app"
        ports:
            -   "8081:8081"
        command: "npm run start"
    mysql:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: nativeip
            MYSQL_DATABASE: nativeip

volumes:
    mysql: