version: "3"

services:
    frontend:
        build:
            context: ./frontend
            target: build-step
        working_dir: /home/app
        environment:
            NODE_ENV: development
            CHOKIDAR_USEPOLLING: 'true'
        ports:
            -   "3000:3000"
        command: "npm run start"
        volumes:
            -   "./frontend/src:/home/app/src"
    backend:
        build:
            context: ./backend
            target: dev
        working_dir: /home/app
        env_file:
            - "./backend/.env"
        volumes:
            -   "./backend/:/home/app"
        ports:
            -   "8081:8081"
        command: "npm run start"
        entrypoint: ["/bin/bash", "./entrypoint.sh"]
    mysql:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        expose:
            -   3306
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: nativeip
            MYSQL_DATABASE: nativeip

volumes:
    mysql: